# 左側を親機（Central）に設定
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# トラックボールセンサーのドライバー有効化
CONFIG_PMW3610=y
CONFIG_PMW3610_CPI=1200
CONFIG_PMW3610_ORIENTATION_180=n
CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=700

# スクロール・スナイプの高度なアルゴリズムを有効化
CONFIG_PMW3610_SMART_ALGORITHM=y
